DexaiRobotics/drake-torch

drake-torch.dockerfile
scripts/fix_bashrc.sh

This removes some nastiness from DexaiRobotics/fullstack:run_fullstack.sh (See DexaiRobotics/fullstack#19)

Fix broken interactive shell detection in bashrc

---

drake-torch.dockerfile

adding an editor to the docker...

add vim to docker

---

.gitignore
drake-torch.dockerfile

add jupyter requirements for docker

add jupyter

---

drake-torch.dockerfile

Tried pip installing `torchvision` but couldn't get any of the binaries to work, so built from source.

Dependencies for live_pytorch

---

scripts/fix_bashrc.sh

change source logic

---

drake-torch.dockerfile

Needed to generate URDFs/workstation YAMLs per https://github.com/DexaiRobotics/salad_bar_description/pull/104

Install python 3 URDF parser from source

---

drake-torch.dockerfile

Added packages `libudev-dev` and `libusb-1.0-0-dev`

Added packages for driver

---

drake-torch.dockerfile

Add espeak + a few other tools from #docker wishlist

---

drake-torch.dockerfile
scripts/fix_bashrc.sh
scripts/setup_pydrake.py

pip install pydrake, eliminating the need for appending it to pythonpath

---

Jenkinsfile
drake-torch.dockerfile

This passed all jenkins build tests including CPU, GPU, and with `dig`. This took a while as the `dig` compatibility tests also depended on `fullstack`.
This stable release will be tagged and pushed and we'll build with nightly drake on jenkins.

msgpack-c setup commands and other updates

---

Jenkinsfile-nightly.groovy
Jenkinsfile-stable.groovy
build.sh
drake-torch.dockerfile

This PR passed build test on Jenkins
http://10.10.223.137:8080/blue/organizations/jenkins/drake-torch-stable/detail/drake-torch-stable/203/pipeline

Separate stable and nightly build pipeline for both CI and DEV images

---

build.sh
drake-torch.dockerfile

adding PR for production code that never got merged

upgrade to CUDA 10.2, two channels for torch and drake

---

build_test_dockers.sh

updated base image tags

---

build.sh
drake-torch.dockerfile

OpenCV 4.4.0 for C++ and python3

---

build.sh
drake-torch.dockerfile

OpenCV 4.4 upgrade + drake jupyter fix

---

build.sh
drake-torch.dockerfile

fix catkin build and pip install failures

---

build.sh
drake-torch.dockerfile
scripts/fix_bashrc.sh

fix cv_bridge import issue due to endianness mismatch

---

scripts/fix_bashrc.sh

Remove unterminated quote

---

build.sh
drake-torch.dockerfile
scripts/fix_bashrc.sh

update toppra install and PS1

---

drake-torch.dockerfile

gtest 1.10

---

drake-torch.dockerfile

purge rosdep gtest 1.7

---

drake-torch-melodic.dockerfile
drake-torch-noetic.dockerfile
drake-torch.dockerfile
in_container_scripts/mod_bashrc.sh
in_container_scripts/run_tests.sh

build `vision_opencv` from source for python3

---

drake-torch-melodic.dockerfile
in_container_scripts/mod_bashrc.sh

add check for py27 path to ensure its presence

---

drake-torch-melodic.dockerfile
drake-torch-noetic.dockerfile
drake-torch.dockerfile

update libtorch cuda version

---

drake-torch-melodic.dockerfile
drake-torch-noetic.dockerfile

remove gazebo and add libusb

---

drake-torch.dockerfile

solve pip install failure

---

build_image.sh
drake-torch.dockerfile

peg stable channel to cuda 11.1 throughout

---

drake-torch-noetic.dockerfile

* cmake configs at `/usr/local/lib/cmake/easy_profiler`
* library at `/usr/local/bin/libeasy_profiler.so`
* use
```
find_package(easy_profiler REQUIRED) 
target_link_libraries(my_application easy_profiler)
```

add easy profiler for c++
